//Key for unlocking the game
EnterYourkey = "10H84-45H83-Z1MH2-D4QN9-G38MK"
//For Better Appearance use 22 characters only!
game.title = "Unscrambe The Letters";
//when no title is set
noname = "Untitled Game"
//allow students to save their name in the browser
allowsavetousename = true;
//save alerts
displaysavealert = false;
//password
requirepassword = false;
//recaptha
recaptha = false;
//login code
logincode = "k";
//errorsolver
errorsolverlogdisplay = false;
//Game

//Game Signature

Signature = "malavika"

//Game Instruction
GameInstruction = "game instructions"

//Questions

//Q1
Question1 = "ycecpildaone"
Question1Answer = "encyclopedia"
HintForQuestion1 = "A Book Which Contains all the information."

//Q2
Question2 = "llohe"
Question2Answer = "hello"
HintForQuestion2 = "Greetings."

//Q3
Question3 = "rergenye"
Question3Answer = "Greenery"
HintForQuestion3 = "green foliage, growing plants, or vegetation."
