//Key for unlocking the game
EnterYourkey = "10H84-45H83-Z1MH2-D4QN9-G38MK"
//For Better Appearance use 22 characters only!
GameTitle = "Tumbling letters";
//when no title is set
noname = "Untitled Game"
//allow students to save their name in the browser
allowsavetousename = true;
//save alerts
displaysavealert = false;
//password
requirepassword = true;
//recaptha
recaptha = true;
//login code
logincode = "WEBINAR";
//errorsolver
errorsolverlogdisplay = false;
//Game

//Game Signature

Signature = "malavika"

//Game Instruction
GameInstruction = "REFER TO THE INSTRUCTIONS GIVEN IN POWER POINT SLIDE"

//Questions

//Q1
Question1 = "ycecpildaone"
Question1Answer = "encyclopedia"
HintForQuestion1 = "A Book Which Contains all the information."

//Q2
Question2 = "ratgyvi"
Question2Answer = "gravity"
HintForQuestion2 = "the universal force of attraction acting between all matter."

//Q3
Question3 = "rergenye"
Question3Answer = "Greenery"
HintForQuestion3 = "green foliage, growing plants, or vegetation."
